### ISSUE TITLE
Add calendar time slot selector

### ISSUE THREAD

**Issue by nicklandgrebe** [GetOccasion/occsn-checkout#14]
## Stories

* As a customer, I want to be able to browse a calendar of time slots, then select a day and choose from time slots for that day, to book my order

## Implementation Plan

Use react-fullcalendar to display `product.constructCalendar` for each month, then set `activeTimeSlots` in data-store for selected day. Display `activeTimeSlots` as a list

## TODO

- [ ] Add `Calendar` container with access to `calendarApp` data-store
- [ ] Call `calendarRef.init()` on Order component init (instead of loading timeSlots for timeSlotSelector)
- [ ] Display full-calendar with requested timeSlots from `constructCalendar` called in `init`
- [ ] Set `activeTimeSlots` for day selected in `Calendar`
- [ ] Add `TimeSlotSelector` component to `Calendar` to display `activeTimeSlots`
- [ ] Add conditional for `product.timeSlotView` that displays `Calendar` (for `calendar`) and `TimeSlotSelector` for `list`
