### ISSUE TITLE
Add session time slot view

### ISSUE THREAD

**Issue by nicklandgrebe** [GetOccasion/occsn-checkout#16]
## Stories

* As a customer, I want to be able to view the time slots of a session I am going to order, or be able to view the time slot I am about to book for an order with only one time slot available

## Implementation Plan

Add `session` prop to `TimeSlotList` that removes the ability to select time slots or browse pages, instead selecting all time slots for the product

## TODO

- [x] Add `session` prop
- [x] Toggle off pagination
- [x] Toggle off selection
- [x] Select all time slots
