### ISSUE TITLE
Convert to exportable boilerplate

### ISSUE THREAD

**Issue by nicklandgrebe** [GetOccasion/occsn-checkout#34]
## Stories

* As a checkout XP developer, I want to be able to import a single component `OccsnCheckout` that magically constructs an entire checkout experience, while allowing me to access product and order to customize their display

## Implementation Plan

Export `AppContainer` from `index.js` and remove custom bootstrap components in favor of adding `.attendees` identity classes to every layer of the boilerplate

## TODOs

- [ ] Define exportable `AppContainer` as `OccsnCheckout`
- [ ] Remove custom bootstrap components in favor of `div`s
- [ ] Add identity classes to all components
- [ ] Allow props to pass in custom components for each component (`attendeesComponent`, `attendeeComponent`, `customerComponent`, etc.)
