### ISSUE TITLE
Add callback props to customize boilerplate

### ISSUE THREAD

**Issue by nicklandgrebe** [GetOccasion/occsn-checkout#35]
## Stories

* As a checkout XP developer, I want to be able to access the order and product each time they change, as well as customize what happens at each interaction with the XP (selecting a time, a date, attendees, etc.)

## Implementation Plan

Add props for each of the possible steps in the checkout XP, as well as `onProductLoad`, and `onOrderChange` for hooking into the product/order data

## TODOs

- [x] Add `onProductLoad` prop to exported component
- [x] Add `onOrderChange` prop
- [x] Add `onDateSelect` prop
- [x] Add `onTimeSelect` prop
- [ ] Add `onOrderComplete` prop
