### ISSUE TITLE
Add pre-fill time slot id

### ISSUE THREAD

**Issue by nicklandgrebe** [GetOccasion/occsn-checkout#44]
## Stories

* As a customer, if I select a product time slot from a calendar, I want it automatically selected when I start booking the order

## Implementation

* Detect window.OCCSN.time_slot_id and select it instead of displaying the time slot selector

## TODOs

- [ ] Detect time_slot_id
- [ ] If time_slot_id, create new TimeSlot with id and assign it to order.timeSlots
- [ ] If time_slot_id, hide time slot selector
